apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-ads-mcp-server
  namespace: prod
  labels:
    app: google-ads-mcp-server
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: google-ads-mcp-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: google-ads-mcp-server
        environment: production
    spec:
      containers:
      - name: google-ads-mcp-server
        image: ghcr.io/your-username/google-ads-mcp:IMAGE_TAG
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: APP_ENV
          value: "prod"
        - name: LOG_LEVEL
          value: "INFO"
        - name: CACHE_ENABLED
          value: "true"
        - name: CACHE_TTL
          value: "3600"
        - name: PORT
          value: "8000"
        envFrom:
        - secretRef:
            name: google-ads-credentials-prod
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: google-ads-mcp-logs
          mountPath: /var/log/google-ads-mcp
      volumes:
      - name: google-ads-mcp-logs
        persistentVolumeClaim:
          claimName: google-ads-mcp-logs-pvc
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - google-ads-mcp-server
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 60 