apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: google-ads-mcp-logs-pvc
  namespace: prod
  labels:
    app: google-ads-mcp-server
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard 