apiVersion: v1
kind: Service
metadata:
  name: google-ads-mcp-server
  namespace: prod
  labels:
    app: google-ads-mcp-server
    environment: production
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: google-ads-mcp-server 