# Google Cloud Operations Configuration for Google Ads MCP Server
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: google-ads-mcp-server-monitoring
  namespace: dev
  labels:
    app: google-ads-mcp-server
spec:
  selector:
    matchLabels:
      app: google-ads-mcp-server
  endpoints:
  - port: 8000
    path: "/metrics"
    interval: 30s  # Scrape every 30 seconds
---
apiVersion: logging.googleapis.com/v1
kind: LogConfig
metadata:
  name: google-ads-mcp-server-logging
  namespace: dev
  labels:
    app: google-ads-mcp-server
spec:
  fluentBit:
    parser:
      json:
        enabled: true
  service:
    # Configure log sink to send to Cloud Logging
    pipelines:
      application:
        input:
          kubernetes:
            labelSelector: "app=google-ads-mcp-server"
        output:
          googleCloud:
            logName: "google-ads-mcp-server"
            resource: "k8s_container"
            labels:
              app: "google-ads-mcp-server"
              component: "application" 