apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-ads-mcp-server
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: google-ads-mcp-server
        env:
        - name: APP_ENV
          value: "prod"
        - name: LOG_LEVEL
          value: "INFO"
        - name: CACHE_ENABLED
          value: "true"
        - name: CACHE_TTL
          value: "7200" 