apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-ads-mcp-server
spec:
  template:
    spec:
      containers:
      - name: google-ads-mcp-server
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi 