apiVersion: v1
kind: Service
metadata:
  name: google-ads-mcp-server
  namespace: dev
  labels:
    app: google-ads-mcp-server
    environment: development
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: google-ads-mcp-server 