apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-ads-mcp-server
  labels:
    app: google-ads-mcp-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: google-ads-mcp-server
  progressDeadlineSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: google-ads-mcp-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: google-ads-mcp-server
        image: gcr.io/PROJECT_ID/google-ads-mcp-server:TAG
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 200m
            memory: 384Mi
          limits:
            cpu: 700m
            memory: 768Mi
        env:
        - name: PORT
          value: "8000"
        - name: CACHE_ENABLED
          value: "true"
        - name: CACHE_TTL
          value: "3600"
        - name: GRACEFUL_SHUTDOWN_TIMEOUT
          value: "25"
        # Monitoring configuration
        - name: ENABLE_METRICS
          value: "true" 
        - name: ENABLE_OTEL
          value: "false"  # Set to true when OpenTelemetry collector is available
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: ""  # Set to your OpenTelemetry collector endpoint
        - name: LOG_FORMAT
          value: "json"
        - name: LOG_LEVEL
          value: "info"
        envFrom:
        - secretRef:
            name: google-ads-credentials
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 5"]
        volumeMounts:
        - name: google-ads-mcp-logs
          mountPath: /var/log/google-ads-mcp
      volumes:
      - name: google-ads-mcp-logs
        emptyDir: {} 