apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
- ../../base
- hpa.yaml
patchesStrategicMerge:
- patches/deployment-patch.yaml
- patches/resource-patch.yaml 