# Debug Deployment Failure (Triggered on failure) - 2025-03-26
# This step is triggered when the verification step fails
# Provides comprehensive debugging information
# Based on the step in cicd.yml

- name: Debug deployment failure
  if: failure()
  run: |
    echo "Checking pod status..."
    kubectl get pods -n dev
    
    echo "Checking deployment details..."
    kubectl describe deployment google-ads-mcp-server -n dev
    
    echo "Getting pod details and logs..."
    POD_NAME=$(kubectl get pods -n dev -l app=google-ads-mcp-server -o jsonpath="{.items[0].metadata.name}")
    if [ -n "$POD_NAME" ]; then
      echo "Pod events and details:"
      kubectl describe pod $POD_NAME -n dev
      echo "Pod logs:"
      kubectl logs $POD_NAME -n dev --all-containers=true
      echo "Previous pod logs (if any):"
      kubectl logs $POD_NAME -n dev --all-containers=true --previous
    fi
    
    echo "Checking node status..."
    kubectl describe nodes
    
    echo "Checking all resources in namespace..."
    kubectl get all -n dev 