apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-ads-mcp-server
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: google-ads-mcp-server
        env:
        - name: APP_ENV
          value: "dev"
        - name: LOG_LEVEL
          value: "DEBUG"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi 