name: Test GKE Authentication

on:
  workflow_dispatch:  # Manual trigger only

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: google-ads-mcp-cluster
  GKE_ZONE: us-central1

jobs:
  test-gke-auth:
    name: Test GKE Authentication
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        
    - name: Debug GCloud Auth
      run: |
        # Check if we can authenticate with gcloud
        gcloud auth list
        gcloud config list
        
    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        project_id: ${{ env.PROJECT_ID }}
        credentials: ${{ secrets.GCP_SA_KEY }}
        
    - name: Verify kubectl access
      run: |
        # Simple kubectl command to test access
        kubectl get nodes
